### ISSUE TITLE
Define Prisma Model for the project

### ISSUE THREAD

**Issue by pedrouzcategui** [pedrouzcategui/todopractice#1]

**Comment by juanzenn** [comment]
Ok

**Comment by AlfredoPrograma** [comment]
Below is my initial proposal for the database structure of the project:

![todopracticedb](https://github.com/pedrouzcategui/todopractice/assets/99158056/abe70f83-f7e6-4fbd-998c-b6aedad80f0f)

Fundamentally, these are the key relationships between entities:

- **Users** can create and belong to multiple **workspaces**.
- **Users** can create or be assigned to multiple **tasks**.
- **Workspaces** can contain multiple **tasks**.

It's important to note that **users** can serve as **workspace administrators**. This means they have the ability to **invite other users, create tasks within the workspace, and assign tasks to other workspace users.**

Additionally, there are several more intricate concepts we can integrate later if the business logic supported by this database structure proves to be easily implementable. These include:

- Implementing **roles** for **workspace users**.
- Introducing **categories** for **tasks**.
- Incorporating **custom statuses** for **tasks** based on the current **workspace.**

These enhancements can be explored once the core functionality of the database is established and operational.

**Comment by pedrouzcategui** [comment]
@juanzenn per the design, I believe custom task stages are not contemplated, just that enum as you see there.

Taking in consideration that this project is a practice project to setup the template for the hackathon, I wouldn't consider it necessary.

**Comment by pedrouzcategui** [comment]
Hi, can I suggest adding a new column called "is_tutorial_finished" in the users table, which defaults to false when creating the user?

This value would change after the tutorial have been finished. 

@AlfredoPrograma

**Comment by AlfredoPrograma** [comment]
> Hola, please add a uuid field to every table:
> 
> * User -> user_uuid
> * Workspace -> workspace_uuid
> * Task -> task_uuid
> 
> Keep the PK as an autoincrement ID. This is better than only having the autoincrement or a CUID. Prefix to make it easier to identify. These UUIDs are the ones being shown in the browser.
> 
> Also, how would this model look with custom task stages?

1. Do you propose make each table to contain two ids; primary key as auto-increment and **uuid** as displayable id?. Why don't use just only one id (autoincrement or uuid)?

2. As @pedrouzcategui said, custom tasks stages are not considered for the first stage of the project. I think they should be considered only when the core project has been implemented and there is time left for improvements.

**Comment by juanzenn** [comment]
One for internal lookup and one for external use. Just a preference  :D

**Comment by AlfredoPrograma** [comment]
> One for internal lookup and one for external use. Just a preference :D

We could do it but I'm not sure what advantages this change brings. I think using only one id for internal and external management is simpler.

**Comment by AlfredoPrograma** [comment]
Done!
