### ISSUE TITLE
Tutorial Page Frontend

### ISSUE THREAD

**Issue by pedrouzcategui** [pedrouzcategui/todopractice#15]
Implement this feature in the application, just frontend, not backend.
![image](https://github.com/pedrouzcategui/todopractice/assets/55967440/160fd8e8-8c1f-4b9c-be70-b50dc76eda6a)

**Comment by pedrouzcategui** [comment]
Is not necessary to use Zustand for this since that state is not going to be shared across all of the application. Change this to use context or useState instead.

**Comment by pedrouzcategui** [comment]
Still on this, will work on it tomorrow

**Comment by juanzenn** [comment]
@pedrouzcategui make updates on PR #20 . If you haven't commit anything else is fine, just update on the PR
