### ISSUE TITLE
Workspace Internal Routes

### ISSUE THREAD

**Issue by juanzenn** [pedrouzcategui/todopractice#37]
We need a route to check users in the workspace.

**Comment by pedrouzcategui** [comment]
@juanzenn Can you expand on the issue?

**Comment by juanzenn** [comment]
The requirements are to create an internal route tree on the workspace view. This means adding these functionalities to the "workspace" route

- Main view - all tasks on list and kanban view
- Settings - workspace settings 
- Users - workspace users and permission management

**Comment by AlfredoPrograma** [comment]
I think this is already done; but there is not any pull request associated with it. I'm gonna close the issue anyways :laughing:. If I am wrong and this is not already done, just reopen the issue.
