### ISSUE TITLE
Implement defined database structure into Prisma schema

### ISSUE THREAD

**Issue by AlfredoPrograma** [pedrouzcategui/todopractice#6]
Once core database structure was defined in the issue #1; now we need to implement the corresponding entities and relationships in the Prisma Schema in order to generate the database changes.

**Comment by pedrouzcategui** [comment]
Hey, would it be possible to add a "created_at", and "due_date" columns to the tasks table?
@AlfredoPrograma

**Comment by pedrouzcategui** [comment]
Hi, would it be possible to add a "deleted_at" to the tasks table? The idea behind this column is to apply a soft delete and archived function. @AlfredoPrograma
